"""empty message

Revision ID: 1b3eb80f8e6c
Revises: 3aac2ee5c993
Create Date: 2017-05-25 10:17:01.215141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3eb80f8e6c'
down_revision = '3aac2ee5c993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitem', sa.Column('bucketlist_id', sa.Integer(), nullable=False))
    op.add_column('bucketlistitem', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('bucketlistitem', sa.Column('id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'bucketlistitem', 'bucketlists', ['bucketlist_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('bucketlistitem', 'status')
    op.drop_column('bucketlistitem', 'item_id')
    op.drop_column('bucketlistitem', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketlistitem', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('bucketlistitem', sa.Column('item_id', sa.INTEGER(), nullable=False))
    op.add_column('bucketlistitem', sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bucketlistitem', type_='foreignkey')
    op.drop_column('bucketlistitem', 'id')
    op.drop_column('bucketlistitem', 'done')
    op.drop_column('bucketlistitem', 'bucketlist_id')
    # ### end Alembic commands ###
